apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: hello-world-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-html 
  template:
    metadata: 
      labels: 
        app: hello-world-html 
    spec: 
      containers:
      - name: hello-world-html 
        image: rashidulapp/hello-world-html
        ports:
        - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: hello-world-html-service
spec:
  selector:
    app: hello-world-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
