apiVersion: v1
kind: PersistentVolume 
metadata:
  name: local-pv-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/Users/rashidulislam/Desktop/PVs"

---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: local-pv-2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/Users/rashidulislam/Desktop/PVs2"
    