apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx  
    spec:  
      containers:
      - name: nginx  
        image: rashidulapp/hello-world-html
        ports:
        - containerPort: 80
        volumeMounts:  
        - name: nginx-pvc
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: local-pvc
