apiVersion: v1
kind: Service 
metadata:
  name: stateless-app-svc
spec:
  selector:
    app: stateless-app 
  ports:
  - port: 8765
    targetPort: 9376
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
